// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_API.Data;

#nullable disable

namespace REST_API.Migrations
{
    [DbContext(typeof(RestApiDBContext))]
    partial class RestApiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REST_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All about programming and software development.",
                            Title = "Coding"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Exploring new places and cultures around the world.",
                            Title = "Traveling"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Capturing moments through the lens.",
                            Title = "Photography"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Creating delicious meals and culinary experiences.",
                            Title = "Cooking"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Enjoying and creating music across various genres.",
                            Title = "Music"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Participating in and watching various sports activities.",
                            Title = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Diving into books and expanding knowledge.",
                            Title = "Reading"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Engaging in video games and interactive entertainment.",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Exploring nature through hiking and outdoor adventures.",
                            Title = "Hiking"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Creating and appreciating various forms of art.",
                            Title = "Art"
                        });
                });

            modelBuilder.Entity("REST_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Bob",
                            LastName = "Brown",
                            PhoneNumber = "444-987-6543"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Charlie",
                            LastName = "Davis",
                            PhoneNumber = "333-222-1111"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Eve",
                            LastName = "Wilson",
                            PhoneNumber = "777-888-9999"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Frank",
                            LastName = "Miller",
                            PhoneNumber = "666-555-4444"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Grace",
                            LastName = "Taylor",
                            PhoneNumber = "222-333-4444"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Hank",
                            LastName = "Anderson",
                            PhoneNumber = "111-222-3333"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Ivy",
                            LastName = "Thomas",
                            PhoneNumber = "888-777-6666"
                        });
                });

            modelBuilder.Entity("REST_API.Models.PersonInterestLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterestLinks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1,
                            Url = "https://example.com/johns-coding-blog"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 2,
                            Url = "https://example.com/janes-travel-vlog"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 3,
                            PersonId = 3,
                            Url = "https://example.com/alices-photo-gallery"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            PersonId = 4,
                            Url = "https://example.com/bobs-cooking-recipes"
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 5,
                            PersonId = 5,
                            Url = "https://example.com/charlies-music-playlist"
                        });
                });

            modelBuilder.Entity("REST_API.Models.PersonInterestLink", b =>
                {
                    b.HasOne("REST_API.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REST_API.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("REST_API.Models.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("REST_API.Models.Person", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
